
PROJECT_NAME: WGAN-ANIME256

DATASET:
  NAME: dataset/anime256
  TRAIN_TEST_RATIO: 1.0

MODEL:
  NAME: WGAN
  D:
    DIMENSION: 64

SOLVER:
  BASE_LR: 1e-4
  BETAS: (0.5,0.999)
  EVALUATE_BATCH: 32
  EVALUATE_ITERATION: 250

IMAGE:
  HEIGHT: 256
  WIDTH: 256

DATALOADER:
  BATCH_SIZE: 16